apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/docker-career-sphere/backend:latest
        ports:
        - containerPort: FRONTEND_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: FRONTEND_PORT
      targetPort: FRONTEND_PORT
  type: LoadBalancer # Exposes frontend to the internet
