services:
  frontend:
    # image: colinmcd6/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:4004
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app

  backend:
    image: colinmcd6/backend:latest
    ports:
      - "4004:4004"
    environment:
      - NODE_ENV=production
      - APP_ORIGIN=http://localhost:5173
      - PORT=4004
      - MONGO_URI=mongodb://mongo:27017/test_db
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    networks:
      - app

volumes:
  mongo-data:

networks:
  app:
    driver: bridge