services:
  frontend:
    image: colinmcd6/frontend:latest-dev
    # build:
    #   context: ./frontend
    #   target: development
    #   args:
    #     VITE_API_URL: https://localhost:4004
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4004
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend
    networks:
      - app

  backend:
    image: colinmcd6/backend:latest-dev
    # build:
    #   context: ./backend
    #   target: development
    ports:
      - "4004:4004"
    environment:
      - NODE_ENV=development
      - APP_ORIGIN=http://localhost:5173
      - PORT=4004
      - MONGO_URI=mongodb://mongo:27017/test_db
      - JWT_SECRET=myjwtsecret
      - JWTREFRESH_SECRET=myjwtrefrestsecret
      - SENDER_EMAIL=test
      - API_RESEND=test
      - RESEND_API_KEY=test
    depends_on:
      - mongo
    networks:
      - app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    networks:
      - app

volumes:
  mongo-data:

networks:
  app:
    driver: bridge