apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/docker-career-sphere/backend:latest
        ports:
        - containerPort: BACKEND_PORT
        env:
        - name: MONGO_URI
          value: "mongodb+srv://MONGODB_USER:MONGODB_PASS@careersphere.ldhzb.mongodb.net/?retryWrites=true&w=majority&appName=CareerSphere"
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "0000"
        - name: JWT_SECRET
          value: JWT_SECRET_VALUE
        - name: JWTREFRESH_SECRET
          value: JWTREFRESH_SECRET_VALUE
        - name: SENDER_EMAIL
          value: aa
        - name: API_RESEND
          value: bb
        - name: RESEND_API_KEY
          value: RESEND_API_KEY_VALUE
        - name: APP_ORIGIN
          value: http://backend-service.default.svc.cluster.local:BACKEND_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: BACKEND_PORT
      targetPort: BACKEND_PORT
  type: ClusterIP