apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/careersphere/docker-career-sphere/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: SENDER_EMAIL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SENDER_EMAIL
        - name: API_RESEND
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: API_RESEND
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PORT
        - name: APP_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: APP_ORIGIN
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: JWT_SECRET
        - name: JWTREFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: JWTREFRESH_SECRET
        - name: RESEND_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: RESEND_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP