name: Build Backend

on:
  push:
    branches:
    - 'deployment'

env:
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
  FRONTEND_PORT: 80
  MONGODB_USER: ${{ secrets.MONGODB_USER }}
  MONGODB_PASS: ${{ secrets.MONGODB_PASS }}
  JWT_SECRET_VALUE: ${{ secrets.JWT_SECRET }}
  JWTREFRESH_SECRET_VALUE: ${{ secrets.JWTREFRESH_SECRET}}
  RESEND_API_KEY_VALUE: ${{ secrets.RESEND_API_KEY }}
  GKE_CLUSTER: autopilot-cluster-careersphere--1
  GKE_REGION: us-central1
  GAR_REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: build and push the backend docker image
      run: |
        gcloud auth configure-docker $GAR_REGION-docker.pkg.dev
        docker build -t $GAR_REGION-docker.pkg.dev/$GOOGLE_PROJECT/docker-career-sphere/backend:latest ./backend
        docker push $GAR_REGION-docker.pkg.dev/$GOOGLE_PROJECT/docker-career-sphere/backend:latest

    - name: build and push the frontend docker image
      run: |
        gcloud auth configure-docker $GAR_REGION-docker.pkg.dev
        docker build -t $GAR_REGION-docker.pkg.dev/$GOOGLE_PROJECT/docker-career-sphere/frontend:latest ./frontend
        docker push $GAR_REGION-docker.pkg.dev/$GOOGLE_PROJECT/docker-career-sphere/frontend:latest

    - name: Get GKE credentials
      run: |
        gcloud components install gke-gcloud-auth-plugin
        gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $GOOGLE_PROJECT

    - name: deploy backend to gke
      run: |
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" ./backend/backend-deployment.yml
        sed -i "s/BACKEND_PORT/$BACKEND_PORT/g" ./backend/backend-deployment.yml
        sed -i "s/MONGODB_USER/$MONGODB_USER/g" ./backend/backend-deployment.yml
        sed -i "s/MONGODB_PASS/$MONGODB_PASS/g" ./backend/backend-deployment.yml
        sed -i "s/JWT_SECRET_VALUE/$JWT_SECRET_VALUE/g" ./backend/backend-deployment.yml
        sed -i "s/JWTREFRESH_SECRET_VALUE/$JWTREFRESH_SECRET_VALUE/g" ./backend/backend-deployment.yml
        sed -i "s/RESEND_API_KEY_VALUE/$RESEND_API_KEY_VALUE/g" ./backend/backend-deployment.yml
        kubectl apply -f ./backend/backend-deployment.yml

    - name: deploy frontend to gke
      run: |
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" ./frontend/frontend-deployment.yml
        sed -i "s/FRONTEND_PORT/$FRONTEND_PORT/g" ./frontend/frontend-deployment.yml
        kubectl apply -f ./frontend/frontend-deployment.yml

