name: Build Backend

on:
  push:
    branches:
    - '43-continous-integration'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v2

    - name: install google cloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run:
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/docker-career-sphere/backend ./backend
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/docker-career-sphere/backend