name: Build and Push Docker Images

on:
  push:
  pull_request:
    branches:
      - development
      - main
    types:
      - closed

jobs:
  build-and-push:
    name: Build and Push Docker Images
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Frontend Image
        run: |
          docker build \
          --target production \
          --build-arg VITE_API_URL=https://api.career-sphere.me \
          -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

      - name: Build and Push Backend Image
        run: |
          docker build \
          --target production \
          -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest ./backend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
            docker compose -f ~/var/www/CareerSphere/compose.prod.yml down
            docker compose -f ~/var/www/CareerSphere/compose.prod.yml up -d