name: Build and Push Docker Images

on:
  push:
    branches:
    - 'deployment'
  pull_request:
    branches:
      - development
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $DOCKER_HUB_USERNAME
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t $DOCKER_HUB_USERNAME/frontend:latest ./frontend
          docker push $DOCKER_HUB_USERNAME/frontend:latest

      - name: Build and Push Backend Image
        run: |
          docker build -t $DOCKER_HUB_USERNAME/backend:latest ./backend
          docker push $DOCKER_HUB_USERNAME/backend:latest