name: Build and Push Docker Images

on:
  pull_request:
    branches:
      - development
      - main
    types:
      - closed

jobs:
  build-and-push:
    name: Build and Push Docker Images
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine Version Tag
        id: version
        run: |
          # Read the current version
          NEW_VERSION=$(cat version.txt)

          # Output the new version
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ env.NEW_VERSION }} ./frontend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ env.NEW_VERSION }}
  
      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend:${{ env.NEW_VERSION }} ./backend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:${{ env.NEW_VERSION }}