name: Sonar
on:
  push:
    branches:
      - development
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is available for analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        continue-on-error: true  # Allows the workflow to continue even if the quality gate fails
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sources=.
            -Dsonar.exclusions=**/test/**,**/tests/**,**/*.test.js
            -Dsonar.qualitygate.wait=false
            -Dsonar.newCode.referenceBranch=main
