name: Run Jest Tests

on:
  pull_request:
    branches:
      - development
      - main
      - test_bryce
      - AccImprove_quizzingFeature
  push:
    branches:
      - test_bryce
      - new_test_bryce

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      APP_ORIGIN: http://localhost:5173
      MONGO_URI: mongodb://localhost:27017/Comp4350_CareerSphere
      PORT: 5050
      JWT_SECRET: myjwtsecret
      JWTREFRESH_SECRET: myjwtrefrestsecret
      SENDER_EMAIL: a
      API_RESEND: bb
      RESEND_API_KEY: uuuu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Set NODE_ENV to test
        run: echo "NODE_ENV=test" >> $GITHUB_ENV

      - name: Start MongoDB Docker Container
        run: |
          sudo docker run -d --name test-mongo -p 27017:27017 mongo:latest
          sudo docker ps -a

      - name: Install Dependencies
        run: npm install --prefix backend

      - name: Run Jest Tests
        run: npm test --prefix backend