name: Run Jest Tests

on: 
  push:
    branches:
      - jest

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use your project's Node.js version
          cache: 'npm'  # Caches node_modules for faster runs

      - name: Install Dependencies
        run: npm install --prefix backend

      - name: Run Jest Tests
        run: npm test --prefix backend # Ensure "test": "jest" is in package.json
